### ISSUE TITLE
Repo is unusable without git-lfs

### ISSUE THREAD

**Issue by aaronjensen** [tecosaur/org-pandoc-import#1]
It looks like you used git-lfs to store `screenshots/csv.png`. If one does not have git-lfs installed, the repo cannot be checked out without erroring, which means it cannot be installed with straight.

**Comment by tecosaur** [comment]
Oh, that's a pain! I can host the images elsewhere, which is one half of the solution. Do you know if/how I can remove lfs?

**Comment by tecosaur** [comment]
Ah, found this: https://gist.github.com/everttrollip/198ed9a09bba45d2663ccac99e662201

**Comment by aaronjensen** [comment]
I'd imagine the images aren't very big, so you could put them in the repo if you'd like. Storing them elsewhere would save a bit of download for folks, but that shouldn't matter if you publish to melpa because i think they'd be stripped. 

As an aside, here's a recipe for use-package + straight.el (once lfs is removed):

```
(use-package org-pandoc-import
  :straight (:host github
                   :repo "tecosaur/org-pandoc-import"
                   :files ("filters" "*.el")))
```

The filters directory won't get installed by default w/o specifying `:files` when using straight.

**Comment by tecosaur** [comment]
Cool, thanks. I'll update things in a bit. I just don't like how it feels to check binary files into git :sweat_smile:

**Comment by tecosaur** [comment]
I guess I probably could though, since they won't exactly be changing much.

**Comment by tecosaur** [comment]
@aaronjensen I think that should be fixed, please let me know :)

**Comment by aaronjensen** [comment]
That works, thanks!
