### ISSUE TITLE
openBinaryFile: does not exist (No such file or directory)

### ISSUE THREAD

**Issue by xiaobing-huang** [tecosaur/org-pandoc-import#11]
Hello tecosaur,

When i try to call below code:
```
(org-pandoc-import-as-org "test" "~/Documents/org/templates/template.docx")
```
got the error:
pandoc: ~/Documents/org/templates/template.docx: openBinaryFile: does not exist (No such file or directory)

But if expand the filename
```
(org-pandoc-import-as-org "test" "/Users/i074455/Documents/org/templates/template.docx")
```
everything works.

I am using MacOS.

**Comment by tecosaur** [comment]
This looks like something `(expand-file-name ...)` should fix. I'll take a look in the next few days.

**Comment by tecosaur** [comment]
Well, that was a terrible estimate. Shouldn't be long till I have time now :crossed_fingers:

**Comment by PRESFIL** [comment]
Any updates on this? Experiencing the same problem on Linux.

It seems like `expand-file-name` is not there.

**Comment by tecosaur** [comment]
Give 84924edff44a4ee278d05511b46dae5329767112  a shot.

**Comment by PRESFIL** [comment]
Both `org-pandoc-import-to-org` and `org-pandoc-import-as-org` works with the
tilde prefix (`~`) in imported path. Thank you!

**Comment by PRESFIL** [comment]
@xiaobing-huang, can you confirm the issue is resolved?

**Comment by xiaobing-huang** [comment]
Yes, it works now.
