### ISSUE TITLE
Should Emacs `cd` to imported file for `pandoc`

### ISSUE THREAD

**Issue by PRESFIL** [tecosaur/org-pandoc-import#13]
Some `pandoc` switches (`--extract-media=`) may contain relative paths, and if
you don't go to the folder with the imported file, `pandoc` will inherit the
current Emacs working folder and work with / clutter a random directory
(usually `~` or `~/.emacd.d` or `~/.config/emacs`). Should Emacs switch this
directory somehow?

**Comment by tecosaur** [comment]
Done in d3cd2b0519b53766a5454155b012e0a75e139ade.
