### ISSUE TITLE
Melpa package

### ISSUE THREAD

**Issue by phuhl** [tecosaur/org-pandoc-import#4]
Hi there, this looks really interesting. I noticed though, that you have to install straight from github. A Melpa package would be rather handy :)

**Comment by tecosaur** [comment]
Sounds like a good idea. I'll try to do this over the next few weeks.

**Comment by tecosaur** [comment]
PR made: https://github.com/melpa/melpa/pull/7326

It took a few weeks, but hey --- it's finally happened.

**Comment by phuhl** [comment]
Nice, thanks and happy new year

**Comment by MartinNowak** [comment]
Would be nice to give it another shot to get https://github.com/melpa/melpa/pull/7326 merged, we're understandably all @tecosaur.
