### ISSUE TITLE
unable to import .ipynb or csv

### ISSUE THREAD

**Issue by laurentHYZ** [tecosaur/org-pandoc-import#6]
Hi Tecosaur, 
I tried org-pandoc-import, it works great with odt and docx files, but I am unable to make it work with ipynb and csv files, each time I tried with those 2 formats I obtained an empty org-file with #+TITLE: test
thank you!

**Comment by tecosaur** [comment]
Could you please provide:
- OS info
- Sample files

**Comment by laurentHYZ** [comment]
Hi Tecosaur,
I am on Ubuntu 20.04.1 LTS, here are 3 sample files,
cheers
laurent
________________________________

**Comment by laurentHYZ** [comment]
mail sent, thank you!

**Comment by laurentHYZ** [comment]
Tecosaur helped me with the issue, as it turns out my pandoc version was too old (2.5).

- I visited https://github.com/jgm/pandoc/releases
- download the latest .deb version (2.11.1.1 at the time I am posting this), 
- Ran the file from  within command line with:
`cd Downloads && sudo dpkg -i pandoc-2.11.1.1-1-amd64.deb`
-went back to emacs and `org-pandoc-import-to-org`

Now everything works great, thank you Tecosaur !

**Comment by laurentHYZ** [comment]
closing the issue!

**Comment by tecosaur** [comment]
Glad you got it working! :slightly_frowning_face:
